installer:
  build: docker-images/installer
  dockerfile: Dockerfile.extended
  environment:
    DOMAIN: dockerized-magento.local
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: pw
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  volumes_from:
    - nginx
  volumes:
    - ./config/installer/php/php.ini:/usr/local/etc/php/php.ini
    - ./config/installer/magerun/n98-magerun.yaml.tmpl:/etc/n98-magerun.yaml.tmpl
    - ./config/installer/magento/local.xml.tmpl:/etc/local.xml.tmpl
    - ./config/installer/magento/fpc.xml.tmpl:/etc/fpc.xml.tmpl
    - ./config/installer/bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    - ./config/installer/bin/install.sh:/bin/install.sh
    - ~/.composer:/root/.composer
    - ~/.ssh:/root/.ssh
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "mysql:mysql"
    - "elasticsearch:elasticsearch"
  entrypoint: /bin/install.sh

nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/nginx/includes:/etc/nginx/includes
    - ./config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  build: docker-images/php
  dockerfile: Dockerfile.extended
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "mysql:mysql"
    - "elasticsearch:elasticsearch"
  environment:
    PHP_IDE_CONFIG: "serverName=dockerized-magento.local"
  volumes:
    - .:/var/www/html
    - ./docker-images/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini:ro
mysql:
  image: mariadb:10.2
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
  volumes:
    - ./data/mysql:/var/lib/mysql
elasticsearch:
  image: elasticsearch:1.5
  environment:
    discovery.type: single-node
    http.host: 0.0.0.0
    transport.host: 127.0.0.1
    script.disable_dynamic: "false"
    script.inline: "on"
    script.indexed: "on"
  volumes:
    - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
  ports:
    - "9300:9300"
    - "9200:9200"
kibana:
  image: kibana:4.0.2
  environment:
    SERVER_NAME: localhost
    ELASTICSEARCH_URL: http://elasticsearch:9200
  ports:
    - "5601:5601"
  links:
    - "elasticsearch:elasticsearch"
cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_PORT: 3306
